spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      INDENT_OUTPUT: true

  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    # url: jdbc:mysql://localhost:3306/zigzag_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    url: jdbc:postgresql://127.0.0.1:5432/ksr_db
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 4

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  base64Secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  jwtExpirationMs: 7200000  # 2 hours
  jwtRefreshExpirationMs: 172800000 # 2 days

logging:
  level:
    org.zerhusen.security: DEBUG
    org.springframework.security: DEBUG

