version: "3.8"

services:
  ksr-mysql:
    image: "mariadb:10.5.8"
    container_name: ksr_mysql
    hostname: local-mysql
    platform: linux/x86_64    # MACOS m1 에서만 필요로하는 옵션
    ports:
      - "3306:3306"
    volumes:
    #   - ./mysqlconf/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./.volumes/mysql/:/var/lib/mysql:rw
    environment:
      MYSQL_DATABASE: ksr_db
      MYSQL_ROOT_PASSWORD: 1234
    labels:
      - "name=database"
      - "environment=dev"

  ksr-redis:
    image: redis:6.2.6-alpine3.15
    container_name: redis
    hostname: local-redis
    ports:
      - "6379:6379"
    volumes:
      - ./.volumes/redis:/bitnami/redis/data
    labels:
      - "name=cache"
      - "environment=dev"

